# Generated by Django 4.2.16 on 2024-11-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VRModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=150)),
                ('frame_number', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=150)),
                ('sensor_data', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'vr3d_info',
            },
        ),
        migrations.CreateModel(
            name='VRUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=13)),
                ('email', models.CharField(default=None, max_length=60, unique=True)),
                ('password', models.CharField(default=True, max_length=60)),
                ('country_id', models.SmallIntegerField(default=1)),
                ('state_id', models.SmallIntegerField(default=1)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default=None, max_length=300)),
                ('address2', models.TextField(default='', max_length=300)),
                ('zip', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'vrusers',
            },
        ),
    ]
